# Generated by Django 4.0.3 on 2022-04-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_response_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='questions',
            new_name='question',
        ),
    ]
