# Generated by Django 4.0.3 on 2022-04-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_answer_post_alter_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='email',
        ),
        migrations.AlterField(
            model_name='answer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.question'),
        ),
    ]
