# Generated by Django 4.0.3 on 2022-04-12 13:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
